# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MixLedger' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MixLedger
  pod 'SwiftLint'
  pod 'SnapKit', '~> 5.6.0'

  target 'MixLedgerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MixLedgerUITests' do
    # Pods for testing
  end

end
